### ISSUE TITLE
Connectivitycheck blocked on Quad9

### ISSUE THREAD

**Issue by ferreum** [GrapheneOS/grapheneos.network#1]
Since some time between 2021-05-02T23:00Z and 2021-05-03T10:00Z connectivitycheck.grapheneos.network is blocked on Quad9. This results in GrapheneOS displaying Wifi connection as having no internet connectivity when selecting the GrapheneOS in the Internet connectivity check menu.

I verified this with a direct query, which returns NXDOMAIN:
```
> dig @9.9.9.9 connectivitycheck.grapheneos.network
; ...
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 63812
; ...
```
This can also be verified with the domain tester: https://www.quad9.net/result?url=connectivitycheck.grapheneos.network
According to that tester it seems to stem from a listing in "DOMAINTOOLS Hotlist".
The whole grapheneos.network domain seems to be affected: https://www.quad9.net/result?url=grapheneos.network

As a personal solution I switched to the "dangerous" version of Quad9, as I have DNSSEC validation and blocklists in my own network.

**Comment by thestinger** [comment]
Please report the problem to them. It's an issue on their end.

**Comment by ferreum** [comment]
@thestinger Thanks, I posted this mainly as an FYI, since others might experience issues because of this.

Good news: the domain seems to have gotten unblocked a few minutes ago.

**Comment by thestinger** [comment]
I'm interested to know how they possibly could have blocked it though. It simply serves 204 responses from /generate_204 and redirects to https://grapheneos.org/faq#default-connections from the root URL.
