### ISSUE TITLE
Bluetooth connectivity

### ISSUE THREAD

**Issue by FrustratedN00b** [GrapheneOS/grapheneos.network#7]
I have a Pixel 4a 5g running GrapheneOS that connects to Bluetooth devices just fine except to a 2019 Volkswagen Jetta. The radio has been reset and it still won't connect. The phone won't even find the car media player when searching. It'll find other devices like normal. 
I have another Pixel 4a 5g running CalyxOS and this one finds and connects to the 2019 VW Jetta with no problem. 
The Pixel with GrapheneOS was gifted to someone and it can't be used on her car, the Jetta. She has to use an audio cable. I'd like to get this fixed for her.

**Comment by thestinger** [comment]
This sounds like a configuration issue. You should factory reset the device. Please get help in our Matrix chat room first rather than here and file the issue again if you can't resolve it with help there. We can't provide support here.
