### ISSUE TITLE
WearOS Connectivity

### ISSUE THREAD

**Issue by DonavynDeRaine** [GrapheneOS/grapheneos.network#8]
I made the change from AndroidOS to GrapheneOS, and I have a few things that still need to be added, my Fossil Gen 6 smartwatch is one of those.

I have the Google Play store installed from the Graphene repository and is successfully sandboxed.  I installed WearOS from Google and began walking through the connection steps.

In those instructions, it makes an initial Bluetooth connection, which tells me was successful.  However, right after the exchange between the phone and watch falter, forcing me to reset the watch and app to try again.

What can I do to set my smart device up so that I can complete the transition of OS?

**Comment by DonavynDeRaine** [comment]
This may be the quickest 'incident report' that you've ever had.

I was finally able to connect my watch after turning on Nearby Devices on the Google app, the Wear OS app, and the Sandboxed Play Store.

Once those had access everything connected.  However, it does make me wonder if the Google app itself can be added as Sandboxed, since sending things to them is what we're not all about.  Just a thought.

**Comment by r3g-5z** [comment]
All apps are sandboxed. Sandboxed Google Play is unprivileged and sandboxed, it operates as any other normal app you install. There isn't anything special or privileged about it on GrapheneOS. If you give it a permission, it will have access to whatever that permission allows it to access, like any other normal app you install. That's how the Android permission moidel works. Please read https://grapheneos.org/usage#sandboxed-google-play as this is answered there.
